import = [
  "~/mainfiles/.config/alacritty/themes/ash.toml"
]

[font]
normal = { family = "FiraCode Nerd Font", style = "Medium" }
bold = { family = "FiraCode Nerd Font", style = "Bold" }
italic = { family = "FiraCode Nerd Font", style = "Italic" }
bold_italic = { family = "FiraCode Nerd Font", style = "Bold Italic" }
size = 7
offset.x = 0
offset.y = 2
glyph_offset.y = 1


[window]
padding = { x = 10, y = 10 }
opacity = 0.5

[cursor]
style = "block"
